apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: qwe-qwe-poi-map-app-dev
  annotations:
    argocd/app-name: qwe-qwe-poi-map-app-dev
    backstage.io/kubernetes-id: qwe-qwe-poi-map-app-dev
    backstage.io/kubernetes-namespace: qwe
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=qwe-qwe-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus1/qwe-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/dev-pipelines/ns/qwe/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23rock.n26o.p1.openshiftapps.com/k8s/ns/qwe/deployments/qwe-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23rock.n26o.p1.openshiftapps.com/#https://github.com/Summit23Janus1/qwe-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://qwe-poi-map-app-qwe.apps.summit23rock.n26o.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/q30000"
  system: workshop-system-qwe
  consumesApis:
    - gateway-api-qwe
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-qwe
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/q30000"
